name: 'CI'

on:
  push:
    branches:
      - 'main'
      - 'master'
    pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Lisp
        uses: 40ants/setup-lisp@v2
        with:
          asdf-system: chobun
      - name: Run tests
        uses: 40ants/run-tests@v2
        with:
          asdf-system: chobun
      
